Feature/tests
Denis-on-github/task_manager pull request #14
Opened 2023-10-11 08:59 UTC by Denis-on-github

2023-10-16 06:46 UTC, aleksandr-semenov-dbp requested changes

2023-10-16 06:46 UTC, aleksandr-semenov-dbp commented on test/base.py
> +    #     cls.client.force_login(cls.user)
Не храним в репозитории закоментированый код

2023-10-16 06:46 UTC, aleksandr-semenov-dbp commented on test/test_user.py
> +        )
не нужно так раскрашивать тесты, их постепенно скапливается довольно много в проекте и, хочется видеть максимально компактный вывод, особенно в (самом частом) случае успешного прохождения, кроме того print() довольно медленная функция

2023-10-16 06:46 UTC, aleksandr-semenov-dbp commented on test/test_user.py
> +        print(f"=== Expected response: {expected_response} ===")
чтобы посмотреть значения для отладки неуспешных рейсов у assert есть второй параметр, в успешных случаях это все не важно как я писал выше

2023-10-16 06:46 UTC, aleksandr-semenov-dbp commented on test/test_user.py
> +        expected_response = self.expected_details(self.test_user, self.user_attributes)
Тесты будут легче читаться если их привести к единому формату - предлагается

1. подготовка к действию
2. проверяемое действие
3. рассчет ожидаемого результата
4. сравнение реального результата и ожидаемого

У себя в коде мы прямо требуем писать всегда так и еще отделяем эти пункты друг от друга пустой строчкой. (Здесь например 1 и 3 поменяны местами, хотя в других тестах не так)

2023-10-16 06:46 UTC, aleksandr-semenov-dbp commented on test/test_user.py
> +        try:
посмотри pytest.raises(), но вообще здесь не требуется работать м исключениями, у себя мы все функции типа create() или retrieve() расщепляем на две - request_retrieve() которая возвращает респонз без проверки, и retrieve() которая ожидает успешной операции. В таких тестах используется вариант без проверки, и только здесь проверяется, что респонз ожидаемый (404). Еще вариант - можно просто убедиться что удаленного объекта нет в list()

2023-10-16 06:46 UTC, aleksandr-semenov-dbp commented on test/test_user.py
> +        assert len(users_list) > 3
не понял почему здесь должно получиться так много записей

2023-10-16 08:22 UTC, Denis-on-github commented on test/base.py
> +    #     cls.client.force_login(cls.user)
Убрал.

2023-10-16 08:24 UTC, Denis-on-github commented on test/test_user.py
> +        )
Да, в будущих ПР я это убрал.

2023-10-16 08:25 UTC, Denis-on-github commented on test/test_user.py
> +        expected_response = self.expected_details(self.test_user, self.user_attributes)
Поправил.

2023-10-16 08:26 UTC, Denis-on-github commented on test/test_user.py
> +        try:
Выбрал последний вариант.

2023-10-16 08:29 UTC, Denis-on-github commented on test/test_user.py
> +        assert len(users_list) > 3
```
users_list = self.list(filters={"first_name": "John_Doe"})
assert len(users_list) > 3
```
Это по сути просто проверка самого фильтра, который фильтрует только по полю `username`, следовательно, когда мы делаем фильтр по другому полю (`first_name`), то возвращается полный список пользователей.

2023-10-23 05:14 UTC, aleksandr-semenov-dbp approved these changes

2023-10-26 08:25 UTC, merged